# Generated by Django 4.2.7 on 2024-01-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_category_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Business', 'Business')], default='General', max_length=100),
        ),
    ]
